config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get '/sobre', to: 'static_pages#about'
  get '/produtos', to: 'static_pages#others_insurances'

  get '/get_drop_down_options', to: 'quotation_steps#get_drop_down_options'
  get '/get_address', to: 'quotation_steps#get_address'

  resources :questions
  resources :quotation_steps
  resources :quotations do
    get :autocomplete_vehicle_model_model, :on => :collection
  end

  get 'quotation/quotation_success', to: 'quotations#quotation_success'
end

app/controllers/quotation_steps_controller.rb
class QuotationStepsController < ApplicationController
  layout "quotation"
  include Wicked::Wizard
  steps :data_vehicle, :use_vehicle, :driver_info, :insured_info, :owner_info

  def show
    @quotation = Quotation.find session[:quotation_id]
    case step
    when :data_vehicle
      @quotation.has_alarm = false
      @quotation.has_blocker_ignition = false
      @quotation.has_tracker = false
      @quotation.funded_alienated = false
      @quotation.has_armor = false
      @quotation.has_gaskit = false
      @quotation.has_chassis_remarked = false

    when :use_vehicle
      @quotation.has_house_park = false
      @quotation.has_house_remote_control = false
      @quotation.use_go_work = false
      @quotation.funded_alienated = false
      @quotation.has_work_park = false
      @quotation.has_work_remote_control = false
      @quotation.use_commercial = false
      @quotation.use_go_study = false
      @quotation.has_study_park = false
      @quotation.has_study_remote_control = false
    end

    render_wizard
  end

  def get_address
    val = params[:cep]
    result = ""
    begin
      address = Correios::CEP::AddressFinder.get(val)
    rescue ArgumentError
      render plain: "CEP inválido"
    else
      result = address[:address] + " - " + address[:neighborhood] + " - " + address[:city] + "/" + address[:state]
      render plain: result  
    end
    

  end

  def get_drop_down_options
    val = params[:year].to_i
    #Use val to find records
    array = [val, val+1]
    render :text => array
  end

  def update
    @quotation = Quotation.find session[:quotation_id]
    case step
    when :data_vehicle
      @quotation.attributes = quotation_data_vehicle_params
    when :use_vehicle
      @quotation.attributes = quotation_use_vehicle_params
    when :driver_info
      @quotation.attributes = quotation_driver_info_params
      if @quotation.driver_is_insured
        @quotation.insured_name = @quotation.driver_name
        @quotation.insured_cpf = @quotation.driver_cpf
        @quotation.insured_gender = @quotation.driver_gender
        @quotation.insured_birth_date = @quotation.driver_birth_date
        @quotation.insured_marital_status = @quotation.driver_marital_status
      else
        @quotation.insured_name = nil
        @quotation.insured_cpf = nil
        @quotation.insured_gender = nil
        @quotation.insured_birth_date = nil
        @quotation.insured_marital_status = nil
        @quotation.insured_email = nil
        @quotation.insured_is_driver = nil
      end

      if @quotation.driver_is_owner
        @quotation.owner_name = @quotation.driver_name
        @quotation.owner_cpf = @quotation.driver_cpf
        @quotation.owner_gender = @quotation.driver_gender
        @quotation.owner_birth_date = @quotation.driver_birth_date
        @quotation.owner_marital_status = @quotation.driver_marital_status
        @quotation.insured_is_owner = false
      else
        @quotation.owner_name = nil
        @quotation.owner_cpf = nil
        @quotation.owner_gender = nil
        @quotation.owner_birth_date = nil
        @quotation.owner_marital_status = nil
        @quotation.owner_email = nil
        @quotation.owner_is_driver = nil
      end      
    when :insured_info
      @quotation.attributes = quotation_insured_info_params
      if ( not @quotation.driver_is_owner) and @quotation.insured_is_owner
        @quotation.owner_name = @quotation.insured_name
        @quotation.owner_cpf = @quotation.insured_cpf
        @quotation.owner_gender = @quotation.insured_gender
        @quotation.owner_birth_date = @quotation.insured_birth_date
        @quotation.owner_marital_status = @quotation.insured_marital_status
        @quotation.owner_email = @quotation.insured_email
        @quotation.insured_is_owner = false
      elsif @quotation.driver_is_owner and @quotation.driver_is_insured
        @quotation.owner_email = @quotation.insured_email
      end      
    when :owner_info
      @quotation.attributes = quotation_owner_info_params
    end    
    @quotation.status = step
    render_wizard @quotation
  end

  private
    def redirect_to_finish_wizard(options = nil)
      @quotation = Quotation.find session[:quotation_id]
      QuotationMailer.quotation_email(@quotation).deliver
      redirect_to quotation_quotation_success_path, notice: ""
    end

    def quotation_data_vehicle_params
      params.require(:quotation).permit(:brand, :manufacturing_year, 
        :model_year, :vehicle_model_name, :vehicle_model_id, :has_alarm, 
        :has_blocker_ignition, :has_tracker, :funded_alienated, 
        :has_armor, :has_gaskit, :has_chassis_remarked)
    end

    def quotation_use_vehicle_params
      params.require(:quotation).permit(:cep, :cep_night, :has_house_park, 
        :has_house_remote_control, :use_go_work, :has_work_park, 
        :has_work_remote_control, :use_commercial, :use_go_study, 
        :has_study_park, :has_study_remote_control, :km_daily)
    end

    def quotation_driver_info_params
      params.require(:quotation).permit(:driver_name, :driver_cpf, :driver_gender,
        :driver_birth_date, :driver_marital_status, :has_driver_dependent, 
        :enabling_time, :home_cep, :has_other_vehicles, :schooling, :professional_activity,
        :was_stolen, :driver_is_insured, :driver_is_owner)
    end

    def quotation_insured_info_params
      params.require(:quotation).permit(:insured_name, :insured_cpf, :insured_email, 
        :insured_gender, :insured_birth_date, :insured_marital_status, 
        :insured_is_driver, :insured_is_owner)
    end

    def quotation_owner_info_params
      params.require(:quotation).permit(:owner_name, :owner_cpf, :owner_email, 
        :owner_gender, :owner_birth_date, :owner_marital_status, 
        :owner_is_driver)
    end
end

app/helpers/quotation_steps_helper.rb
module QuotationStepsHelper
end

app/views/quotation_steps/data_vehicle.html.erb
<script type="text/javascript">
$( document ).ready(function() {
  $("#quotation_brand").change(function(){
    $( "#quotation_manufacturing_year" ).prop( "disabled", false );
  });

  $("#quotation_manufacturing_year").change(function(){
    $( "#quotation_model_year" ).prop( "disabled", false );

    var url = '/get_drop_down_options.json?year=' + $(this).val()
    $("#quotation_model_year").empty();
    $.get( url, function( data ) {
      $('#quotation_model_year').append("<option value></option>");
      $.each(data, function(i, item) {
        $('#quotation_model_year').append($('<option>', { 
          value: item,
          text : item 
        }));
      });
    })
  });

  $("#quotation_model_year").change(function(){
    $( "#quotation_vehicle_model_name" ).prop( "disabled", false );
    $( "#quotation_vehicle_model_name" ).attr("placeholder", "Ex.: Gol");
    });
  });

</script>
<div id="data_vehicle" class="content-section-b">

  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="row bs-wizard" style="border-bottom:0;">
        
        <div class="col-xs-2 bs-wizard-step complete">
          <div class="text-center bs-wizard-stepnum">1</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Dados básicos</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step active"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">2</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Sobre o veículo</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step disabled"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">3</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Uso do veículo</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
          <div class="text-center bs-wizard-stepnum">4</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Condutor principal</div>
        </div>

        <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
          <div class="text-center bs-wizard-stepnum">5</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Segurado</div>
        </div>

        <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
          <div class="text-center bs-wizard-stepnum">6</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Proprietário</div>
        </div>
      </div>
      <hr class="section-heading-spacer">
      <div class="clearfix"></div>
      <h2 class="section-heading">Sobre o veículo</h2>
    </div>
    <%= simple_form_for(@quotation, url: wizard_path,  html: { class: 'form-horizontal' }) do |f| %>
      <div class="col-md-8 col-md-offset-2">
        

        <div class="well">
          <%= f.input :brand, collection: VehicleBrand.order(:brand).map { |r| [r.brand.upcase,r.id] } %>
          <%= f.input :manufacturing_year, disabled: true, collection: 1999..Date.today.year %>
          <%= f.input :model_year, disabled: true, collection: 1999..Date.today.year %>

          <%= f.input :vehicle_model_name, :url => autocomplete_vehicle_model_model_quotations_path, :id_element => '#quotation_vehicle_model_id', :as => :autocomplete, :fields => {:brand_id => '#quotation_brand', :model_year => '#quotation_model_year'}, disabled: true %>
          <%= f.input :vehicle_model_id, as: :hidden %>
        </div>
        <div class="well">
          <%= f.input :has_alarm, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
          <%= f.input :has_blocker_ignition, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
          <%= f.input :has_tracker, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
          <%= f.input :funded_alienated, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
          <%= f.input :has_armor, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
          <%= f.input :has_gaskit, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
          <%= f.input :has_chassis_remarked, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
        </div>
        <div class="well col-xs-12">
            <%= f.button :submit, t("buttons.continue"), :class => "btn btn-primary pull-right" %>
        </div>
      </div>  
    <% end %>
  </div>  
</div>  

app/views/quotation_steps/driver_info.html.erb
<script type="text/javascript">
  $( document ).ready(function() {
    $('.cpf').mask('999.999.999-99', {reverse: true});
    $('.date').mask('99/99/9999', {reverse: true});  
  });


</script>
<div id="driver_info" class="content-section-b">

  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="row bs-wizard" style="border-bottom:0;">
        
        <div class="col-xs-2 bs-wizard-step complete">
          <div class="text-center bs-wizard-stepnum">1</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Dados básicos</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">2</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Sobre o veículo</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">3</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Uso do veículo</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step active"><!-- active -->
          <div class="text-center bs-wizard-stepnum">4</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Condutor principal</div>
        </div>

        <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
          <div class="text-center bs-wizard-stepnum">5</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Segurado</div>
        </div>

        <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
          <div class="text-center bs-wizard-stepnum">6</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Proprietário</div>
        </div>
      </div>
      <hr class="section-heading-spacer">
      <div class="clearfix"></div>
      <h2 class="section-heading">Condutor principal</h2>
      <p class="bg-info">
        O condutor principal é quem usa o veículo por ao menos 5 dias da semana. Se o veículo for dividido entre diversos condutores, o principal será o condutor mais jovem que usa o veículo por ao menos 2 dias da semana.
      </p>
    </div>
      <%= simple_form_for(@quotation, url: wizard_path,  html: { class: 'form-horizontal' }) do |f| %>
          <div class="col-md-8 col-md-offset-2">
            <div class="well">
              <%= f.input :driver_name %>
              <%= f.input :driver_cpf, :as => :string, input_html: { class: :cpf } %>
              <%= f.input :driver_gender, as: :radio_buttons, collection: [['Masculino', 'Masculino'] ,['Feminino', 'Feminino']] %>
              <% unless f.object.driver_birth_date.nil? %>
                <%= f.input :driver_birth_date, :as => :string, input_html: { class: :date, :value => localize(f.object.driver_birth_date, format: "%d/%m/%Y") } %>
              <% else %>
                <%= f.input :driver_birth_date, :as => :string, input_html: { class: :date } %>
              <% end %>
              <%= f.input :driver_marital_status, collection: [ "Solteiro", "Casado ou união estável", "Separado", "Divorciado", "Viúvo"] %>
              <%= f.input :has_driver_dependent, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
              <%= f.input :enabling_time %>
              <%= f.input :has_other_vehicles, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
              <%= f.input :schooling , collection: ["Pós-Graduação","Superior","Técnico","Médio (2º Grau)","Fundamental completo (1º Grau)","Fundamental ncompleto 1º Grau incompleto)"] %>
              <%= f.input :professional_activity , collection: ["Selecione uma opção","Não trabalha","Advogado(a), Juiz(a) de Direito ou Promotor(a) de Justiça","Aposentado","tleta","Ator, Atriz ou Jornalista","Dentista","Engenheiro(a)/Arquiteto(a)","Estudante","Médico(a)","Militar o Exército/Marinha/Aeronáutica","Músico(a)","Policiais, Guardas-Civis Municipais ou Agentes de Trânsito","rofessor(a) (ensino básico, ensino fundamental, médio ou superior)","Professor(a) Educação Física ou ersonal rainer","Proprietário de Empresas/Negócios","Servidor Público/Funcionário Público","Venda/Representante omercial","Corretor de Seguro / Funcionário CLT Corretora","Outros","Não desejo informar"] %>
              <%= f.input :was_stolen, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
              <%= f.input :driver_is_insured, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
              <%= f.input :driver_is_owner, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
            </div>
            <div class="well col-xs-12">
                <%= f.button :submit, t("buttons.continue"), :class => "btn btn-primary pull-right" %>
            </div>
          </div>
      <% end %>
    </div>    
  </div>    
</div>  

app/views/quotation_steps/insured_info.html.erb
<script type="text/javascript">
  $( document ).ready(function() {
    $('.cpf').mask('999.999.999-99', {reverse: true});
    $('.date').mask('99/99/9999', {reverse: true});  
  });
</script>

<div id="driver_info" class="content-section-b">

  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="row bs-wizard" style="border-bottom:0;">
        
        <div class="col-xs-2 bs-wizard-step complete">
          <div class="text-center bs-wizard-stepnum">1</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Dados básicos</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">2</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Sobre o veículo</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">3</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Uso do veículo</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step complete"><!-- active -->
          <div class="text-center bs-wizard-stepnum">4</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Condutor principal</div>
        </div>

        <div class="col-xs-2 bs-wizard-step active"><!-- active -->
          <div class="text-center bs-wizard-stepnum">5</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Segurado</div>
        </div>

        <div class="col-xs-2 bs-wizard-step disabled"><!-- active -->
          <div class="text-center bs-wizard-stepnum">6</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Proprietário</div>
        </div>
      </div>
      <hr class="section-heading-spacer">
      <div class="clearfix"></div>
      <h2 class="section-heading">Segurado</h2>
      <p class="bg-info">
        Segurado é a pessoa que contratará o seguro em seu benefício pessoal ou de terceiros.
      </p>
    </div>
    <%= simple_form_for(@quotation, url: wizard_path,  html: { class: 'form-horizontal' }) do |f| %>
      <div class="col-md-8 col-md-offset-2">
        <div class="well">
          <%= f.input :insured_name %>
          <%= f.input :insured_cpf, :as => :string, input_html: { class: :cpf } %>
          <%= f.input :insured_email %>
          <%= f.input :insured_gender , as: :radio_buttons, collection: [['Masculino', 'Masculino'] ,['Feminino', 'Feminino']] %>
          <% unless f.object.insured_birth_date.nil? %>
            <%= f.input :insured_birth_date, :as => :string, input_html: { class: :date, :value => localize(f.object.insured_birth_date, format: "%d/%m/%Y") } %>
          <% else %>
            <%= f.input :insured_birth_date, :as => :string, input_html: { class: :date } %>
          <% end %>
          <%= f.input :insured_marital_status, collection: [ "Solteiro", "Casado ou união estável", "Separado", "Divorciado", "Viúvo"] %>
          <% if @quotation.not_found_owner? %>
            <%= f.input :insured_is_owner, as: :radio_buttons, :collection => [[t("buttons.sim"),true], [t("buttons.nao"),false]] %>
          <% end %>
        </div>
        <div class="well col-xs-12">
          <%= f.button :submit, t("buttons.continue"), :class => "btn btn-primary pull-right" %>
        </div>
      </div>  
    <% end %>
  </div>  
</div>  

app/views/quotation_steps/owner_info.html.erb
<script type="text/javascript">
  $( document ).ready(function() {
    $('.cpf').mask('999.999.999-99', {reverse: true});
    $('.date').mask('99/99/9999', {reverse: true});  
  });
</script>

<div id="owner_info" class="content-section-b">

  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="row bs-wizard" style="border-bottom:0;">
        <div class="col-xs-2 bs-wizard-step complete">
          <div class="text-center bs-wizard-stepnum">1</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Dados básicos</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">2</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Sobre o veículo</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step complete"><!-- complete -->
          <div class="text-center bs-wizard-stepnum">3</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Uso do veículo</div>
        </div>
        
        <div class="col-xs-2 bs-wizard-step complete"><!-- active -->
          <div class="text-center bs-wizard-stepnum">5</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Condutor principal</div>
        </div>

        <div class="col-xs-2 bs-wizard-step complete"><!-- active -->
          <div class="text-center bs-wizard-stepnum">6</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Segurado</div>
        </div>

        <div class="col-xs-2 bs-wizard-step active"><!-- active -->
          <div class="text-center bs-wizard-stepnum">7</div>
          <div class="progress"><div class="progress-bar"></div></div>
          <a href="#" class="bs-wizard-dot"></a>
          <div class="bs-wizard-info text-center">Proprietário</div>
        </div>
      </div>
      <hr class="section-heading-spacer">
      <div class="clearfix"></div>
      <h2 class="section-heading">Proprietário</h2>
      <p class="bg-info">
        Proprietário do veículo é a pessoa que consta no documento do veículo.
      </p>
    </div>
    <%= simple_form_for(@quotation, url: wizard_path,  html: { class: 'form-horizontal' }) do |f| %>
      <div class="col-md-8 col-md-offset-2">
        <div class="well col-md-12">
          <%= f.input :owner_name %>
          <%= f.input :owner_cpf, :as => :string, input_html: { class: :cpf } %>
          <%= f.input :owner_email %>
          <%= f.input :owner_gender , as: :radio_buttons, collection: [['Masculino', 'Masculino'] ,['Feminino', 'Feminino']] %>
          <% unless f.object.owner_birth_date.nil? %>
            <%= f.input :owner_birth_date, :as => :string, input_html: { class: :date, :value => localize(f.object.owner_birth_date, format: "%d/%m/%Y") } %>
          <% else %>
            <%= f.input :owner_birth_date, :as => :string, input_html: { class: :date } %>
          <% end %>
          <%= f.input :owner_marital_status, collection: [ "Solteiro", "Casado ou união estável", "Separado", "Divorciado", "Viúvo"] %>
          
        </div>
        <div class="well col-xs-12">
          <%= f.button :submit, t("buttons.finish"), :class => "btn btn-primary pull-right" %>
        </div>
      </div>
      
    <% end %>
  </div>
</div>  