config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get '/sobre', to: 'static_pages#about'
  get '/produtos', to: 'static_pages#others_insurances'

  get '/get_drop_down_options', to: 'quotation_steps#get_drop_down_options'
  get '/get_address', to: 'quotation_steps#get_address'

  resources :questions
  resources :quotation_steps
  resources :quotations do
    get :autocomplete_vehicle_model_model, :on => :collection
  end

  get 'quotation/quotation_success', to: 'quotations#quotation_success'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insurance_type.rb
class InsuranceType < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  validates :vehicle_model, :presence => true, :if => :active?
  
  validates :contact_name, :contact_email, :insurance_type, :presence => true
  
  validates :brand, :manufacturing_year, :model_year, :vehicle_model_name, :presence => true, :if => :data_vehicle?
  
  validates :cep_night, :km_daily, :presence => true, :if => :use_vehicle?
  
  validates :driver_name, :driver_cpf, :driver_gender, :driver_birth_date, 
    :driver_marital_status, :enabling_time, :presence => true, :if => :driver_info?

  validates_inclusion_of :has_driver_dependent, :has_other_vehicles, 
    :was_stolen, :driver_is_insured, :driver_is_owner, :in => [true, false], 
    message: 'não pode ficar em branco', :if => :driver_info?

  validates :insured_name, :insured_cpf, :insured_email, :insured_gender, 
    :insured_birth_date, :insured_marital_status, :presence => true, :if => :insured_info?

  validates_inclusion_of :insured_is_owner, :in => [true, false], 
    message: 'não pode ficar em branco', :if => :insured_info?

  validates :owner_name, :owner_cpf, :owner_email, :owner_gender, 
    :owner_birth_date, :owner_marital_status, :presence => true, :if => :owner_info?

  validate :option_must_be_selected, :if => :data_vehicle?

  def option_must_be_selected
    errors.add(:vehicle_model_name, 'Um modelo da lista deve ser selecionado') if vehicle_model_id.blank? and data_vehicle?
  end


  def active?
    status == 'active'
  end

  def data_vehicle?
    status == 'data_vehicle'
  end

  def use_vehicle?
    status == 'use_vehicle'
  end

  def driver_info?
    status == 'driver_info'
  end

  def insured_info?
    status == 'insured_info'
  end

  def owner_info?
    status == 'owner_info'
  end

  def not_found_owner?
    not driver_is_owner
  end

  belongs_to :vehicle_model, optional: true
  belongs_to :insurance_type

  attr_accessor :brand
  attr_accessor :manufacturing_year
  attr_accessor :model_year
  attr_accessor :vehicle_model_name
end

app/models/vehicle_brand.rb
class VehicleBrand < ApplicationRecord
end

app/models/vehicle_model.rb
class VehicleModel < ApplicationRecord
  belongs_to :vehicle_brand
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @question = Question.new
  end

  def about
    
  end 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    @question = Question.new(question_params)
    
 
    if @question.save
      QuestionMailer.question_email(@question).deliver
    end

    redirect_to home_path
  end

  private
    def question_params
      params.require(:question).permit(:name, :email, :phone, :message)
    end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  layout "quotation"
  autocomplete :vehicle_model, :model, :full => true

  def new
    @quotation = Quotation.new
  end

  def create
    @quotation = Quotation.new(quotation_params)
    if @quotation.save
      session[:quotation_id] = @quotation.id
      redirect_to quotation_steps_path
    else
      render :new
    end

    
  end

  def quotation_success
    
  end

  def autocomplete_vehicle_model_model
    term = params[:term]
    brand_id = params[:brand_id]
    model_year = params[:model_year]
      vehicles = VehicleModel.where(
        'LOWER(vehicle_models.model) ILIKE ? and vehicle_brand_id = ? and year = ?', "%#{term}%", "#{brand_id}", "#{model_year}"
        ).order('LOWER(vehicle_models.model)').all
      render :json => vehicles.map { |profile| {:id => profile.id, :label => profile.model, :value => profile.model} }
  end

  private
    def quotation_params
      params.require(:quotation).permit(:contact_name, :contact_email, :insurance_type_id)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  autocomplete :vehicle_model, :model, :full => true

  def new
    @quote = Quote.new
  end

  def data_vehicle
    @vehicle_quote = VehicleQuote.new
  end

  def autocomplete_vehicle_model_model
    term = params[:term]
    brand_id = params[:brand_id]
    model_year = params[:model_year]
      vehicles = VehicleModel.where(
        'LOWER(vehicle_models.model) ILIKE ? and vehicle_brand_id = ? and year = ?', "%#{term}%", "#{brand_id}", "#{model_year}"
        ).order('LOWER(vehicle_models.model)').all
      render :json => vehicles.map { |profile| {:id => profile.id, :label => profile.model, :value => profile.model} }
  end

  def use_vehicle
    @use_vehicle_quote = UseVehicleQuote.new
  end

  def vehicle_driver

  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "quotation"
end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_boolean(boolean)
    boolean ? 'Sim' : 'Não'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quotation_steps_helper.rb
module QuotationStepsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AK Seguros</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render "shared/menu" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/quotation.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkSegurosSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render "shared/menu_quotation" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <p class="copyright text-muted small">Copyright &copy; Footstep Web 2016. All Rights Reserved</p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_menu.html.erb
<!-- Navigation -->
<script type="text/javascript">
    $(document).ready(function () {
        $(".page-scroll").click(function(event) {
            $(".navbar-collapse").collapse('hide');
        });
    });
</script>
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to root_path, class: "navbar-brand topnav" do %>
                <%= image_tag("logo2.png", :class => "img-responsive") %>
            <% end %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to "Sobre", sobre_path %>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Produtos <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a class="page-scroll" href="#auto">Automóvel</a></li>
                        <li><a class="page-scroll" href="#residencial">Residencial</a></li>
                        <li><a class="page-scroll" href="#empresarial">Empresarial</a></li>
                        <li><a class="page-scroll" href="#nautico">Náutico</a></li>
                        <li><%= link_to "Outros", produtos_path %></li>
                    </ul>
                </li>
                <li>
                    <a class="page-scroll" href="#seguradoras">Seguradoras</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contato</a>
                </li>
                <li>
                    <%= link_to "Orçamento", new_quotation_path, class: "page-scroll" %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/shared/_menu_quotation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to root_path, class: "navbar-brand topnav" do %>
                <%= image_tag("logo2.png", :class => "img-responsive") %>
            <% end %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to "Sobre", sobre_path %>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Produtos <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Automóvel", root_path(anchor: 'auto') %></li>
                        <li><%= link_to "Residencial", root_path(anchor: 'residencial') %></li>
                        <li><%= link_to "Empresarial", root_path(anchor: 'empresarial') %></li>
                        <li><%= link_to "Náutico", root_path(anchor: 'nautico') %></li>
                        <li><%= link_to "Outros", produtos_path %></li>
                    </ul>
                </li>
                <li>
                    <%= link_to "Seguradoras", root_path(anchor: 'seguradoras') %>
                </li>
                <li>
                    <%= link_to "Contato", root_path(anchor: 'contact') %>
                </li>
                <li>
                    <%= link_to "Orçamento", new_quotation_path, class: "page-scroll" %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>